name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 193.164.150.235
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          command_timeout: 15m
          script: |
            curl -fsSL https://raw.githubusercontent.com/SergeyGusev1/barbershop-site/main/server_deploy.sh | bash
